
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace mmwl.AMQP.ASN1Classes.Just {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Slice", IsSet = false  )]
    public class Slice : IASN1PreparedElement {
                    
	private string periodStart_ ;
	[ASN1String( Name = "", 
        StringType = UniversalTags.UTCTime , IsUCS = false )]
        [ASN1Element ( Name = "periodStart", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public string PeriodStart
        {
            get { return periodStart_; }
            set { periodStart_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<Counter> counters_ ;
	
[ASN1SequenceOf( Name = "", IsSetOf = false  )]

    
        [ASN1Element ( Name = "counters", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<Counter> Counters
        {
            get { return counters_; }
            set { counters_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Slice));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
